name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.x
    - name: Restore dependencies
      run: dotnet restore smart-id-net-client.sln
    - name: Build
      run: dotnet build smart-id-net-client.sln --no-restore -c Release
    - name: Test
      run: dotnet test smart-id-net-client.sln --no-build -c Release --verbosity normal --filter "Category!=DemoIntegrationReadme"

    - name: README demo integration (optional)
      continue-on-error: true
      run: dotnet test smart-id-net-client.sln --no-build -c Release --verbosity normal --filter "Category=DemoIntegrationReadme"
